### ISSUE TITLE
Ready for Symfony 3.0

### ISSUE THREAD

**Issue by CoalaJoe** [eymengunay/EoHoneypotBundle#13]
In Symfony 2.8 your Bundle throws a deprecated notice.

You need to add the configureOptions() Function to replace the setDefaultOptions() Function in HoneypotType.

**Comment by iisisrael** [comment]
I submitted a PR for this, but the integration tests won't pass.  Setting `composer.json` to require Symfony 2.8 breaks on composer update, because the `eo/symfony-test-edition` dev package has a hard upper limit set at 2.6, so I didn't commit that change.

**Comment by peschee** [comment]
This has been done in #14
