### ISSUE TITLE
Add new version tag

### ISSUE THREAD

**Issue by stefantalen** [eymengunay/EoHoneypotBundle#15]
Since the documentation says we should add the bundle with `dev-master` I'm currently getting failed requirements when updating composer since the dev-master requires symfony 3.0 and my project runs on ~2.3

**Comment by eymengunay** [comment]
Hi @stefantalen ,

You should try [v1.0.1](https://github.com/eymengunay/EoHoneypotBundle/releases/tag/1.0.1), which is the last compatible with symfony 2.3.

**Comment by stefantalen** [comment]
👍
