### ISSUE TITLE
Create new tag for symfony 3.x

### ISSUE THREAD

**Issue by robertfausk** [eymengunay/EoHoneypotBundle#16]
By now the last tag is for symfony 2.x https://github.com/eymengunay/EoHoneypotBundle/releases/tag/1.0.1

Can you create a new tag for symfony 3.x please?

**Comment by eymengunay** [comment]
@robertfausk Thanks for the heads up.

https://github.com/eymengunay/EoHoneypotBundle/releases/tag/v1.1.0
