### ISSUE TITLE
add ability to not raise FormError when honeypot is filled

### ISSUE THREAD

**Issue by robertfausk** [eymengunay/EoHoneypotBundle#17]
My use case is as follows:
I have kind of a registration form.
If a bot or a bot writer fills out all fields then:
- the registration mail should not be send
- there should be no error information in frontend so that the bot can't validate it's form submit

**Comment by eymengunay** [comment]
Hello @robertfausk ,
Thank you for your suggestions but I'm afraid I don't currently have the time to add new features. Please feel free to send a PR :)
