### ISSUE TITLE
Template reference not found

### ISSUE THREAD

**Issue by Aricura** [eymengunay/EoHoneypotBundle#24]
Using Symfony 4.2.4 and HoneypotBundle 1.2.1 I get a `Twig_Error_Loader` Exception because your template can't be found/resolved.
`Template reference "EoHoneypotBundle:Form:div_layout.html.twig" not found, did you mean "@EoHoneypot/Form/div_layout.html.twig"?`

I suggest using the `@EoHoneypot/Form/div_layout.html.twig` resource instead of `EoHoneypotBundle:Form:div_layout.html.twig` in your `FormCompilerPass` class.

**Comment by eymengunay** [comment]
I have merged it, thank you for the pr!

**Comment by Aricura** [comment]
May you please create a new Tag for this bugfix in order to use it?

**Comment by eymengunay** [comment]
[v1.2.2](https://github.com/eymengunay/EoHoneypotBundle/releases/tag/v1.2.2) is now online!
