### ISSUE TITLE
`FilterResponseEvent` renamed to ResponseEvent

### ISSUE THREAD

**Issue by seho-nl** [eymengunay/EoHoneypotBundle#34]
The implemented RedirectListener is not working anymore since Symfony 4.4+

> Since Symfony 4.3, most of the event classes were renamed. The following old classes were deprecated:
> ...
> `FilterResponseEvent` renamed to [ResponseEvent](https://github.com/symfony/symfony/blob/4.3/src/Symfony/Component/HttpKernel/Event/ResponseEvent.php)

See: https://symfony.com/doc/4.3/components/http_kernel.html#creating-an-event-listener

Because version 2.0 suggests to support Symfony 5, this must be changed as well.

**Comment by eymengunay** [comment]
Hi @seho-nl,

thank you for the heads up! This is on me, I should have checked the last PR thoroughly but unfortunately I'm not actively using/developing for Symfony anymore and I missed this entirely.

Pinging @ehibes to see if they can push a fix for it.

**Comment by seho-nl** [comment]
No problem.
Made a pull request with the changes required. You can check it out.

**Comment by eymengunay** [comment]
Thank you @seho-nl! I have merged your PR and created [v2.0.1](https://github.com/eymengunay/EoHoneypotBundle/releases/tag/v2.0.1)
